[project]
name = "a-maze-ing"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "mazegen",
    "mlx",
    "pydantic>=2.13.4",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.21",
    "mypy>=2.1.0",
    "pytest",
]

[tool.uv.sources]
mlx = { path = "mlx-2.4-py3-none-any.whl" }
mazegen = { path = "mazegen-1.0.0-py3-none-any.whl" }

